from __future__ import annotations

from contextlib import AbstractContextManager
from pathlib import Path, PurePath
from typing import Protocol

from deployment.models import BaselineRecord, DeploymentRecord, WriterRunCounts
from deployment.overlay import OverlayArtifact
from deployment.target import DeployTarget


class AirflowReadAdapter(Protocol):
    def capture_pause_state(self, dag_ids: tuple[str, ...]) -> dict[str, bool]: ...

    def writer_run_counts(self, dag_ids: tuple[str, ...]) -> WriterRunCounts: ...


class AirflowMutationAdapter(Protocol):
    def pause_dag(self, target: DeployTarget, dag_id: str) -> None: ...

    def unpause_dag(self, target: DeployTarget, dag_id: str) -> None: ...


class ComposeAdapter(Protocol):
    def validate_candidate(self, target: DeployTarget, overlay_file: PurePath) -> None: ...

    def deploy_code_services(
        self, target: DeployTarget, overlay_file: PurePath, services: tuple[str, ...]
    ) -> None: ...


class GitAdapter(Protocol):
    def detached_checkout(self, repository: str, candidate_sha: str, checkout_root: PurePath) -> PurePath: ...


class HealthAdapter(Protocol):
    def read_health(
        self, target: DeployTarget, expected_overlay: OverlayArtifact
    ) -> str: ...


class Clock(Protocol):
    def utc_now(self) -> str: ...

    def monotonic(self) -> float: ...

    def sleep(self, seconds: float) -> None: ...


class OverlayStore(Protocol):
    def stage(self, artifact: OverlayArtifact) -> Path: ...

    def install(self, staged: Path, artifact: OverlayArtifact) -> None: ...

    def verify_installed(self, expected: OverlayArtifact) -> None: ...

    def restore(self, content: bytes, sha256: str) -> None: ...

    def discard(self, staged: Path) -> None: ...


class DeploymentLedgerAdapter(Protocol):
    def acquire_lock(self, deployment_id: str) -> AbstractContextManager[None]: ...

    def begin(self, record: DeploymentRecord) -> None: ...

    def complete(self, record: DeploymentRecord) -> None: ...

    def record_baseline(self, record: BaselineRecord) -> None: ...

    def previous_success(self, target_fingerprint: str) -> DeploymentRecord | None: ...

    def baseline(self, target_fingerprint: str) -> BaselineRecord | None: ...

    def already_successful(self, deployment_id: str) -> bool: ...

    def read_summary(self) -> dict[str, object]: ...
