name: Deploy Main

on: workflow_dispatch

permissions:
  contents: read

jobs:
  disabled:
    name: disabled
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Deployment disabled
        run: echo disabled
